services:
  - type: web
    name: gift-marketplace
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: BOT_TOKEN
        value: 7683164433:AAFxayNf9scLwZD-tWjO0Gy9KH1_9UrwDe8
  - type: static
    name: gift-frontend
    env: static
    staticPublishPath: frontend/dist